import Navbar from "@/app/user/widgets/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "User - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="relative w-full h-[100vh]">
      {children}
      <Navbar />
    </div>
  );
}
